### PR TITLE
Spiral Lane integration

### PR DESCRIPTION
**Pull request by agalbachicar**
# 🎉 New feature

Solves #265 

## Summary

Integrates the SpiralGroundCurve into the builder to get RoadGeometries that support that ground geometry.

~Note that there are still some issues with tolerances which are underlying to the implementation in #276. The integration is achieved but the tolerance level is extremely high for SmallTownRoads.xodr at the moment.~

Picture of an intersection with spiral geometries from SmallTownRoads.xodr

image

Full mesh file: 

[SmallTownRoadsMesh.zip](https://github.com/maliput/maliput_malidrive/files/15081130/SmallTownRoadsMesh.zip)

## Test it

Via unit and integration tests.

## Checklist
- [x] Signed all commits for DCO
- [x] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if it affects the public API)

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Review by francocipollone — DISMISSED** [review]
LGTM!

**Comment by agalbachicar** [comment]
[c211f7e](https://github.com/maliput/maliput_malidrive/pull/277/commits/c211f7ecf184bb544f8857cb2518b5993b6dfa61) fixes the ground curve issues. Now, it is loading with the right tolerance.

**Review by francocipollone — APPROVED** [review]
LGTM

**Comment by agalbachicar** [comment]
https://github.com/maliput/maliput_malidrive/pull/277/commits/1fae47929e73f5e36729673142ec5d91c0595930 should fix the bazel pipeline.

**Pull request merged**
