### PR TITLE
Replaces the implementation to avoid using explicit drake imported types

### PR DESCRIPTION
**Pull request by agalbachicar**
# 🎉 New feature

Pairs with https://github.com/maliput/maliput/pull/603

## Summary

Replaces direct use of drake / eigen types by new classes  in maliput.

## Test it

Via unit tests.

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if it affects the public API)

action-ros-ci-repos-override: https://gist.githubusercontent.com/francocipollone/b218a7671b9bb6b6be2c22ac19f85793/raw/734e35d0727e61f3f345b448fab0969ec21f5880/maliput_malidrive.repos

### CODE REVIEW

**Comment by francocipollone** [comment]
Note: Added the `action-ros-ci-repos-override`. As of next push it should run CI with the correspondant maliput branch.

**Review by francocipollone — APPROVED** [review]
LGTM! Great you fixed the tests! 

PS: Bazel build is failing

**Comment by agalbachicar** [comment]
For the record:
- Wheel Generation / manylinux2014  failed because of not switching branches.
- gcc / Compile and Test (Bazel) (pull_request) failed because it requires a new maliput release.

**Comment by francocipollone** [comment]
Retriggered CI to see how it behaves after solving the blockers

**Pull request merged**
