### PR TITLE
Fixes include folder installation.

### PR DESCRIPTION
**Pull request by francocipollone**
Part of https://github.com/maliput/maliput_infrastructure/issues/275

action-ros-ci-override: https://gist.githubusercontent.com/francocipollone/18dfba70fefe81314bc8a68138732f53/raw/f87e9a6f8e2a6241fbe79db063158bfca5972b41/prs.repos

### CODE REVIEW

**Review by tfoote — APPROVED** [review]
LGTM. This won't pass CI until https://github.com/maliput/maliput_drake/pull/23 or https://github.com/maliput/maliput/pull/508#pullrequestreview-1005012770 are merged, released, and rebuilt.

**Comment by francocipollone** [comment]
> LGTM. This won't pass CI until [maliput/maliput_drake#23](https://github.com/maliput/maliput_drake/pull/23) or [maliput/maliput#508 (review)](https://github.com/maliput/maliput/pull/508#pullrequestreview-1005012770) are merged, released, and rebuilt.

 - [ ] https://github.com/ros/rosdistro/pull/33562

**Comment by francocipollone** [comment]
`maliput` and `maliput_drake` have been built already, It should be ok now to be re-triggered.
I tried to retrigger it but I am not sure if I am a bit rusty with jenkins or if I don't have the bits to retrigger it. :D @tfoote

**Comment by tfoote** [comment]
You can request a retry from Jenkins by commenting here like this.

@ros-pull-request-builder retest this please

**Comment by tfoote** [comment]
The build passed, but has linter errors which are why it shows error now.

**Comment by francocipollone** [comment]
Issues were solved via 221 and 222.
Build farm should be happy now.

When merging we should: **Rebase and Merge**

**Comment by francocipollone** [comment]
@tfoote Issues are resolved! https://build.ros2.org/job/Fpr__maliput_malidrive__ubuntu_focal_amd64/8/

**Review by tfoote — APPROVED** [review]
I'm glad it wasn't too much to clear the warnings.

**Pull request merged**
